(function(){
function setView(view){document.querySelectorAll('[data-view-panel]').forEach(el=>el.classList.toggle('view-hidden',el.dataset.viewPanel!==view));document.querySelectorAll('.main-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));localStorage.setItem('verdi_active_view',view);if(view==='historial'&&typeof renderHistoryMonth==='function')renderHistoryMonth();}
function monthKeyFromTs(ts){if(!ts)return '';const d=new Date(ts);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function selectedMonth(){return $('historyMonth').value||monthKeyFromTs(Date.now())}
function historyRowsForMonth(){const month=selectedMonth();const rows=typeof buildHistory==='function'?buildHistory():[];return rows.filter(r=>monthKeyFromTs(r.ts||r.exitTs||r.entryTs)===month||monthKeyFromTs(r.exitTs)===month||monthKeyFromTs(r.entryTs)===month)}
function renderHistoryMonth(){const month=selectedMonth();const rows=historyRowsForMonth();const body=$('history');if(!body)return;body.innerHTML=rows.slice(0,500).map(x=>`<tr><td><b>${x.dept}</b></td><td><b>${x.plate}</b><br><small>${x.owner}</small></td><td>${x.exitDate}<br><b>${x.exitTime}</b></td><td>${x.entryDate}<br><b>${x.entryTime}</b></td><td>${x.spaces}</td><td><span class="badge ${x.status==='DENTRO'?'in':'out'}">${x.status}</span></td></tr>`).join('')||'<tr><td colspan="6">No hay registros para el mes seleccionado.</td></tr>';$('historySummary').textContent=`${rows.length} permanencia(s) del mes seleccionado`}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function downloadMonth(){const month=selectedMonth();const rows=historyRowsForMonth();const header=['Dpto.','Placa','Responsable','Salida fecha','Salida hora','Entrada fecha','Entrada hora','Estacionamiento','Estado'];const lines=[header,...rows.map(x=>[x.dept,x.plate,x.owner,x.exitDate,x.exitTime,x.entryDate,x.entryTime,x.spaces,x.status])].map(r=>r.map(csvCell).join(';'));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`VERDI_control_permanencias_${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function initUI(){const hm=$('historyMonth');if(hm){hm.value=monthKeyFromTs(Date.now());hm.addEventListener('change',renderHistoryMonth)}$('downloadMonth').onclick=downloadMonth;document.querySelectorAll('.main-tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));const saved=localStorage.getItem('verdi_active_view')||'registro';setView(saved);renderHistoryMonth();}
const oldRender=window.render;window.render=function(){oldRender();renderHistoryMonth()};
window.addEventListener('DOMContentLoaded',initUI);if(document.readyState!=='loading')initUI();
})();