(function(){
function setView(view){document.querySelectorAll('[data-view-panel]').forEach(el=>el.classList.toggle('view-hidden',el.dataset.viewPanel!==view));document.querySelectorAll('.main-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));localStorage.setItem('verdi_active_view',view);if(view==='historial')renderHistoryMonth();}
function monthKey(ts){if(!ts)return '';const d=new Date(Number(ts));return isNaN(d)?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function dateKey(ts){if(!ts)return '';const d=new Date(Number(ts));return isNaN(d)?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function timeKey(ts){if(!ts)return '';const d=new Date(Number(ts));return isNaN(d)?'':`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function selectedMonth(){return $('historyMonth').value||monthKey(Date.now())}
function csvSplit(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function filteredHistory(){
 const rows=typeof buildHistory==='function'?buildHistory():[];const month=selectedMonth();const day=$('historyDay').value;const from=$('historyFrom').value;const to=$('historyTo').value;const plates=csvSplit($('historyPlates').value).map(canonicalPlate);const depts=csvSplit($('historyDepts').value);
 return rows.filter(r=>{
  const exitTs=Number(r.exitTs||0), entryTs=Number(r.entryTs||0), relevant=[exitTs,entryTs].filter(Boolean);const ts=relevant[0]||Number(r.ts||0);if(month&&relevant.length&&!relevant.some(x=>monthKey(x)===month))return false;if(day&&relevant.length&&!relevant.some(x=>dateKey(x)===day))return false;if(from&&to&&relevant.length&&!relevant.some(x=>{const t=timeKey(x);return t>=from&&t<=to}))return false;if(plates.length&&!plates.includes(canonicalPlate(r.plate)))return false;if(depts.length&&!depts.includes(String(r.dept||'')))return false;return true;
 });
}
function renderHistoryMonth(){const rows=filteredHistory();const body=$('history');if(!body)return;body.innerHTML=rows.slice(0,1000).map(x=>`<tr><td><b>${x.dept}</b></td><td><b>${x.plate}</b><br><small>${x.owner}</small></td><td>${x.exitDate}<br><b>${x.exitTime}</b></td><td>${x.entryDate}<br><b>${x.entryTime}</b></td><td>${x.spaces}</td><td><span class="badge ${x.status==='DENTRO'?'in':'out'}">${x.status}</span></td></tr>`).join('')||'<tr><td colspan="6">No hay registros para los filtros seleccionados.</td></tr>';$('historySummary').textContent=`${rows.length} registro(s) encontrados`}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function downloadMonth(){const rows=filteredHistory();const header=['Dpto.','Placa','Responsable','Salida fecha','Salida hora','Entrada fecha','Entrada hora','Estacionamiento','Estado'];const lines=[header,...rows.map(x=>[x.dept,x.plate,x.owner,x.exitDate,x.exitTime,x.entryDate,x.entryTime,x.spaces,x.status])].map(r=>r.map(csvCell).join(';'));const month=selectedMonth();const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`VERDI_control_permanencias_${month||'filtros'}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function initUI(){const hm=$('historyMonth');if(hm){hm.value=monthKey(Date.now());hm.addEventListener('change',renderHistoryMonth)}['historyDay','historyFrom','historyTo','historyPlates','historyDepts'].forEach(id=>$(id).addEventListener('input',renderHistoryMonth));$('applyHistory').onclick=renderHistoryMonth;$('downloadMonth').onclick=downloadMonth;document.querySelectorAll('.main-tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));const saved=localStorage.getItem('verdi_active_view')||'registro';setView(saved);renderHistoryMonth();}
const oldRender=window.render;window.render=function(){if(typeof oldRender==='function')oldRender();renderHistoryMonth();};
window.addEventListener('DOMContentLoaded',initUI);if(document.readyState!=='loading')initUI();
})();