from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
marker='<!-- Verdi UI correction patch v23 -->'
if marker in s: raise SystemExit(0)
patch=r'''<!-- Verdi UI correction patch v23 -->
<script>
(function(){
function esc23(x){return String(x??'').replace(/[&<>\"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\\':'\\','"':'&quot;'}[m]})}
function park23(v){return String(v&&v.authorized_parking_spaces||'').split(',')[0].trim()||'—'}
function dept23(v){return typeof deptCode==='function'?deptCode(v&&v.department_id):'—'}
function bas23(v){var n=park23(v);if(n==='—')return '—';var q=(spaces||[]).find(function(x){return String(x.space_number)===n});return q&&q.basement||(typeof basementFor==='function'?basementFor(n):'—')}
function special23(v){return !!(v&&v.is_frequent||v&&v.relationship==='visita')}
function last23(v){return (events||[]).filter(function(e){return e.vehicle_id===v.id}).sort(function(a,b){return new Date(a.event_time)-new Date(b.event_time)}).pop()}
function row23(v,k){var a=k==='S'?'salida':'entrada';var tag=v&&v.is_frequent?'VISITA FRECUENTE':(v&&v.relationship==='visita'?'VISITA':'');var b=k==='F'?'':'<button type="button" class="v23move" data-a="'+a+'" data-id="'+esc23(v.id)+'">'+k+'</button>';return '<div class="v23row"><div class="v23first"><span>'+(tag?'<span class="v23tag">'+tag+'</span> ':'')+'<b>'+esc23(v.plate||v.code_label)+'</b> • D '+esc23(dept23(v))+' • '+esc23(park23(v))+' • '+esc23(bas23(v))+'</span>'+b+'</div>'+(k==='F'?'<div class="v23second">'+esc23(v.responsible_name||'—')+' - '+esc23(v.relationship==='visita'?'Visita':v.relationship||'—')+'</div>':'')+'</div>'}
async function refresh23(){var r=await Promise.all([sb.from('vehicles').select('*').eq('building_id',BUILDING_ID).order('created_at',{ascending:false}),sb.from('access_events').select('*').eq('building_id',BUILDING_ID).order('event_time',{ascending:true}),sb.from('parking_spaces').select('*').eq('building_id',BUILDING_ID).order('space_number'),sb.from('departments').select('*').eq('building_id',BUILDING_ID).order('code')]);for(var x of r)if(x.error)throw x.error;vehicles=r[0].data||[];events=r[1].data||[];spaces=r[2].data||[];depts=r[3].data||[];render23()}
async function move23(action,id){try{var v=(vehicles||[]).find(function(x){return x.id===id});if(!v){setMsg('msg','No se encontró el vehículo.');return}var cur=inside(v);if(action==='salida'&&!cur){setMsg('msg','El vehículo ya no figura dentro.');await refresh23();return}if(action==='entrada'&&cur){setMsg('msg','El vehículo ya figura dentro.');await refresh23();return}var now=new Date().toISOString();var source=v.is_frequent?'frecuente':(v.relationship==='visita'?'visita':'residente');var r=await sb.from('access_events').insert({event_time:now,movement:action,source_type:source,vehicle_id:v.id,visitor_id:null,department_id:v.department_id||null,person_id:v.person_id||null,plate:v.plate||v.code_label||null,vehicle_type:v.vehicle_type||'auto',description:v.description||null,worker_name:user&&user.email||profile&&profile.email||'—',client_event_id:String(Date.now())+'-'+Math.random(),synced_at:now,parking_space_id:v.parking_space_id||null,building_id:BUILDING_ID});if(r.error)throw r.error;await refresh23();setMsg('msg',action==='entrada'?'Ingreso registrado correctamente.':'Salida registrada correctamente.',true)}catch(e){console.error(e);setMsg('msg','No se pudo registrar el movimiento: '+(e&&e.message||e))}}
function bind23(box){box.querySelectorAll('.v23move').forEach(function(b){b.onclick=async function(){if(b.disabled)return;b.disabled=true;try{await move23(b.dataset.a,b.dataset.id)}finally{b.disabled=false}}})}
function render23(){var i=document.getElementById('insideList');if(i){var l=(vehicles||[]).filter(function(v){return !v.deleted_at&&(special23(v)?inside(v):(inside(v)||!(events||[]).some(function(e){return e.vehicle_id===v.id})))});i.innerHTML=l.map(function(v){return row23(v,'S')}).join('')||'No hay vehículos dentro.';bind23(i)}var r=document.getElementById('recentList');if(r){var ex=new Set((events||[]).filter(function(e){return e.movement==='salida'}).map(function(e){return e.vehicle_id}));var l2=(vehicles||[]).filter(function(v){return !v.deleted_at&&!inside(v)&&(special23(v)||ex.has(v.id))}).sort(function(a,b){return new Date(last23(b)?.event_time||0)-new Date(last23(a)?.event_time||0)});r.innerHTML=l2.map(function(v){return row23(v,'I')}).join('')||'No hay vehículos para registrar ingreso.';bind23(r)}var f=document.getElementById('visitList');if(f){var l3=(vehicles||[]).filter(function(v){return !v.deleted_at&&v.is_frequent});f.innerHTML=l3.map(function(v){return row23(v,'F')}).join('')||'No hay visitas frecuentes.'}}
window.move=move23;window.render=render23;window.load=refresh23;
var st=document.createElement('style');st.textContent='.v23row{padding:7px 4px;border-bottom:1px solid #eee;font-size:13px}.v23first{display:flex;align-items:center;gap:7px;min-height:34px}.v23first>span{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v23move{width:34px!important;min-width:34px!important;height:34px!important;padding:0!important;border-radius:6px!important;font-weight:700!important}.v23second{font-size:12px;color:#64748b;margin-top:2px}.v23tag{background:#ffeb3b;color:#000;font-weight:800;padding:1px 4px;border-radius:3px}';document.head.appendChild(st);setTimeout(function(){try{render23()}catch(e){}},500)
})();
</script>
'''
s=s.replace('</body>',patch+'\n</body>',1);p.write_text(s,encoding='utf-8')